CXXFLAGS= -Os -fomit-frame-pointer
override CXXFLAGS+= -Wall -fsigned-char
CXX=i686-w64-mingw32-g++

default: all

all: vvm.exe

clean:
	-$(RM) vvm.exe vvm.exe.o

vvm.exe: vvm.exe.o
	$(CXX) $(CXXFLAGS) -o vvm.exe vvm.exe.o -static -static-libgcc -static-libstdc++
vvm.exe.o:
	$(CXX) -o vvm.exe.o -c vvm.cpp
