CXXFLAGS= -Os -fomit-frame-pointer
override CXXFLAGS+= -Wall -fsigned-char
CXX=i686-w64-mingw32-g++

default: all

all: vvmtool.exe

clean:
	-$(RM) vvmtool.exe vvm.w32.o

%.w32.o : %.cpp
	$(CXX) -o $@ -c $<

vvmtool.exe: vvm.w32.o
	$(CXX) -o vvmtool.exe $^ -static -static-libgcc -static-libstdc++

vvm.w32.o: vvm.cpp vvm.h util.h
